<?php

return [

    //DO NOT EDIT THIS FILE. All edits should be made in the .env file and then php artisan config:cache should be run to cache the changes.

    'token' => env('CRON_JOB_TOKEN'),

];
