<?php

return [

    //DO NOT EDIT THIS FILE. All edits should be made in the .env file and then php artisan config:cache should be run to cache the changes.

    'name_short' => env('VATUSA_FACILITY'),
    'name_long' => env('ARTCC_NAME'),
    'email' => env('ARTCC_EMAIL'),
    'email_login' => env('ARTCC_EMAIL_LOGIN'),
    'setmore' => env('ARTCC_SETMORE'),
    'h_hours' => env('HOME_CONTROLLER_HOURS'),
    'v_hours' => env('VISIT_CONTROLLER_HOURS'),
    'class_b' => env('ARTCC_CLASS_B'),
    'class_c' => env('ARTCC_CLASS_C'),
    'class_d' => env('ARTCC_CLASS_D'),
    'all_fields' => env('ARTCC_CLASS_B').', '.env('ARTCC_CLASS_C').', '.env('ARTCC_CLASS_D').', '.env('ARTCC_OBS'),
    'enroute' => env('ARTCC_ENROUTE'),
    'obs' => env('ARTCC_OBS'),

    'front_ctr' => env('FRONT_PAGE_CTR'),
    'front_mjr' => env('FRONT_PAGE_MAJOR'),
    'front_mnr' => env('FRONT_PAGE_MINOR'),
    'front_ctr_d' => env('FRONT_PAGE_CTR_D'),
    'front_mjr_d' => env('FRONT_PAGE_MAJOR_D'),
    'front_mnr_d' => env('FRONT_PAGE_MINOR_D'),

    'vatstar' => env('VATSTAR'),
    'teamspeak' => env('TEAMSPEAK'),

];
