<?php

return [

    //DO NOT EDIT THIS FILE. All edits should be made in the .env file and then php artisan config:cache should be run to cache the changes.

    'facility' => env('VATUSA_FACILITY'),
    'jwk' => env('VATUSA_ULS_JWK'),
    'api_key' => env('VATUSA_API_KEY'),

];
